version: '2'
services:
  sql-linux:
    image: microsoft/mssql-server-linux
    volumes:
    - //C/dev/sqlserver/data:/var/opt/mssql
    ports:
    - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=NicoBolender4SQL*
    networks: 
      - backend


networks:
  backend:
    driver: bridge